Repository gilgeori-goreuda/backend, pull requests merged in 2023-11, with the labels that each got.

#44 feature/#34 리뷰 댓글 등록 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCommentRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
Labels: feature🌱

#45 feature/#34-리뷰 댓글 조회기능 구현
  src/main/java/com/pd/gilgeorigoreuda/common/page/PageInfo.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
Labels: feature🌱

#47 Feature/#43 address search
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ImageRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/AddressSearchListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/AddressSearchResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/FoodCategoryListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/FoodCategoryResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/resources/application-local.yml
Labels: feature🌱

#51 feature/#40 new place,feature/#42 hot place
  src/main/java/com/pd/gilgeorigoreuda/home/controller/HomeController.java
  src/main/java/com/pd/gilgeorigoreuda/home/dto/response/PlaceListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/home/dto/response/PlaceResponse.java
  src/main/java/com/pd/gilgeorigoreuda/home/service/HomeService.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
Labels: feature🌱

#49 feature/#34-리뷰 댓글 업데이트 구현:
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewComment.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
Labels: feature🌱

#30 feature/#27 top 10 database 생성, top 10 insert, getAll 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/statistics/controller/HotPlaceController.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/HotPlace.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/HotPlaceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/HotPlaceService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#54 feature/#34-리뷰 댓글 삭제 구현:
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
Labels: feature🌱

#55 bg/real time hot place
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/controller/HotPlaceController.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/HotPlace.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/Keyword.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/KeywordResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/event/KeywordEvent.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/HotPlaceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/HotPlaceService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java
Labels: feature🌱

#58 feature/#32 가게 찜 추가 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StorePreferenceController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreference.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreferenceType.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StorePreferenceService.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/package-info.java
  src/main/resources/application-local.yml
Labels: feature🌱

#57 Feature/#48 category search
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
Labels: feature🌱

#60 feature/#19/#34 댓글 CRUD 구현
  src/main/java/com/pd/gilgeorigoreuda/common/page/PageInfo.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewComment.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCommentRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
Labels: feature🌱

#61 feature/#18 리뷰 모아보기 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java
  src/main/java/com/pd/gilgeorigoreuda/community/service/CommunityService.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
Labels: feature🌱

#63 refacotr/#56-real-time-hot-place-refactor
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/controller/HotPlaceController.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/HotPlaceListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/HotPlaceResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/HotPlaceService.java
Labels: refactor🛠️

#67 refactor/#66 가게의 도로명주소 타입을 String 에서 StreetAddress 임베디드 타입으로 변경
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StreetAddress.java
Labels: refactor🛠️

#65 feature/#62 request validation, 평점 Double-> Integer로 변경
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCommentCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
Labels: feature🌱, refactor🛠️

#69 feature/(#13)(#17)(#39) store domain 관련 비즈니스 로직
  src/main/java/com/pd/gilgeorigoreuda/common/config/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/MemberActiveInfo.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/MemberLevel.java
  src/main/java/com/pd/gilgeorigoreuda/member/exception/NoSuchMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/member/exception/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodType.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/PurchaseType.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreReportHistory.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreType.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StreetAddress.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/BusinessDateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/FoodCategoryRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreCreateResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreOwnerResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreUpdateResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/AlreadyExistInBoundaryException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/BusinessDateResponseReflectionException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoOwnerMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreException.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreNativeQueryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java
  src/test/java/com/pd/gilgeorigoreuda/store/repository/StoreRepositoryTest.java
Labels: feature🌱

#70 feature/#41/#46 my reviews preference stores
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/HealthController.java
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/member/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/PreferredStoreInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/StoreReporterResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/service/MemberService.java
  src/main/java/com/pd/gilgeorigoreuda/member/service/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreference.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepositoryTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/RepositoryTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ServiceTest.java
  src/test/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepositoryTest.java
  src/test/resources/application-test.yml
Labels: feature🌱

#72 feature/#41/#46 my page 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/HealthController.java
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/member/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/PreferredStoreInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/StoreReporterResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/member/service/MemberService.java
  src/main/java/com/pd/gilgeorigoreuda/member/service/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepositoryTest.java
Labels: feature🌱

#74 refactor/#73 줄바꿈, 대소문자, 라인정렬 수정
  src/main/java/com/pd/gilgeorigoreuda/common/page/PageInfo.java
  src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java
  src/main/java/com/pd/gilgeorigoreuda/community/service/CommunityService.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCommentCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCommentResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewImageRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/controller/HotPlaceController.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/HotPlace.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/HotPlaceListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/HotPlaceResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/KeywordResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/HotPlaceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreRepository.java
  src/test/java/com/pd/gilgeorigoreuda/home/controller/HomeControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepositoryTest.java
  src/test/java/com/pd/gilgeorigoreuda/store/repository/StoreRepositoryTest.java
Labels: refactor🛠️

#75 refactor/#76 review 리뷰 등록 수정
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
Labels: feature🌱

#79 setting/#78 RestDocs 세팅
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/pd/gilgeorigoreuda/home/controller/HomeControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/restdocs/RestDocsConfiguration.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
Labels: setting💻

#80 Feature/#71 file upload
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/common/config/S3Config.java
  src/main/java/com/pd/gilgeorigoreuda/fileUpload/service/FileUploadService.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#83 Feature/#77 store controller unit test
  src/docs/asciidoc/index.adoc
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/GlobalControllerAdvice.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/AddressSearchResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/FoodCategoryRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreUpdateResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreNativeQueryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java
  src/main/resources/application-local.yml
  src/test/java/com/pd/gilgeorigoreuda/home/controller/HomeControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
Labels: refactor🛠️, test🩺

#86 feature/#82 report false report filtering
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreReportHistory.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/ReportCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreReportHistoryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#90 feature/#87 본인이 신고한 가게만 신고취소 가능하도록 만듬
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreReportHistory.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoRepoterMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreReportHistoryException.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreReportHistoryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#88 refactor/#85 erd refactor, add final
  src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java
  src/main/java/com/pd/gilgeorigoreuda/home/dto/response/PlaceListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/Member.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewComment.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewPreference.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewCommentRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewCommentService.java
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/AddressSearchListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/FoodCategoryListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/controller/HotPlaceController.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/HotPlace.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/Keyword.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/HotPlaceListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/HotPlaceResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/KeywordResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/HotPlaceService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodType.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/PurchaseType.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreReportHistory.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreType.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreNativeQueryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreRepository.java
Labels: refactor🛠️

#92 feature/#89 cors origin 과 method 추가
  src/main/java/com/pd/gilgeorigoreuda/common/config/web/CorsConfig.java
Labels: feature🌱

#95 refactor/#94 controller endpoint 수정
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StorePreferenceController.java
Labels: refactor🛠️

#96 feature/#91 check report
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportHistoryListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportHistoryResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportMemberResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchReportException.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreReportHistoryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java
Labels: feature🌱

#98 feature/#93 가게 방문하기 요청 기능
  src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisitRecord.java
  src/main/java/com/pd/gilgeorigoreuda/visit/controller/VisitController.java
  src/main/java/com/pd/gilgeorigoreuda/visit/dto/request/VisitRequest.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/OutOfBoundaryException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/repository/StoreVisitRecordRepository.java
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
  src/test/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculatorTest.java
Labels: feature🌱

#101 Feature/#81 카카오 signup login 기능 구현
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/auth/controller/AuthController.java
  src/main/java/com/pd/gilgeorigoreuda/auth/dto/response/LoginResponse.java
  src/main/java/com/pd/gilgeorigoreuda/auth/exception/EmailDuplicatedException.java
  src/main/java/com/pd/gilgeorigoreuda/auth/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/auth/service/AuthService.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/web/CorsConfig.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/fileUpload/service/FileUploadService.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/Member.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#106 refactor/#105-community-sort-desc로 변경
  src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java
Labels: refactor🛠️

#108 refactor/#107 위경도 전체 자릿수와 소수점 자릿수 지정
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
Labels: refactor🛠️

#110 feature/#82/#87/#91/#97 신고하기 기능 및 필터링
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreReportHistory.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/ReportCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportHistoryListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportHistoryResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportMemberResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/AlreadyReporterMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/LimitDistanceReportException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoRepoterMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchReportException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreReportHistoryException.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StoreReportHistoryRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#112 refactor/#103 image upload 모듈화
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/common/config/AsyncConfig.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/S3Config.java
  src/main/java/com/pd/gilgeorigoreuda/common/decorater/MdcTaskDecorator.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/GlobalControllerAdvice.java
  src/main/java/com/pd/gilgeorigoreuda/fileUpload/service/FileUploadService.java
  src/main/java/com/pd/gilgeorigoreuda/image/ImageUploader.java
  src/main/java/com/pd/gilgeorigoreuda/image/contorller/ImageController.java
  src/main/java/com/pd/gilgeorigoreuda/image/domain/ImageFile.java
  src/main/java/com/pd/gilgeorigoreuda/image/domain/S3ImageDeleteEvent.java
  src/main/java/com/pd/gilgeorigoreuda/image/dto/response/ImagesResponse.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/EmptyImageListException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/ExceedImageCapacityException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/ExceedImageListSizeException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/FileImageNameHashException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/ImageNullException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/InvalidImageFileException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/InvalidImagePathException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/InvalidImageUrlException.java
  src/main/java/com/pd/gilgeorigoreuda/image/listener/S3ImageDeleteEventListener.java
  src/main/java/com/pd/gilgeorigoreuda/image/service/ImageService.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/resources/application-local.yml
Labels: feature🌱, refactor🛠️

#115 feature/#113 각 로깅 레벨별 로깅 파일 분리 작성
  .gitignore
  logs/error/2023-11-13.log
  logs/info/2023-11-13.log
  logs/warn/2023-11-13.log
  src/main/java/com/pd/gilgeorigoreuda/common/config/RequestLoggingConfig.java
  src/main/java/com/pd/gilgeorigoreuda/common/filter/MdcLoggingFilter.java
  src/main/java/com/pd/gilgeorigoreuda/common/filter/RequestLoggingFilter.java
  src/main/resources/console-appender.xml
  src/main/resources/error-appender.xml
  src/main/resources/info-appender.xml
  src/main/resources/logback.xml
  src/main/resources/warn-appender.xml
Labels: feature🌱

#118 feature/#114 가게 아이디로 리뷰 조회하기
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewMemberResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#119 feature/#117 review like hate
  logs/error/2023-11-13.log
  logs/info/2023-11-13.log
  logs/warn/2023-11-13.log
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewPreferenceController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewPreference.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewPreferenceType.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewPreferenceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewPreferenceService.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#121 feature/#116 리뷰 등록시 이미지 업로드 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewImage.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
Labels: feature🌱

#123 feature/#122 가게 이미지 업데이트 또는 가게 삭제시 기존 이미지 삭제 처리 로직
  .gitignore
  logs/error/2023-11-13.log
  logs/info/2023-11-13.log
  logs/warn/2023-11-13.log
  src/main/java/com/pd/gilgeorigoreuda/image/ImageUploader.java
  src/main/java/com/pd/gilgeorigoreuda/image/domain/ImageFile.java
  src/main/java/com/pd/gilgeorigoreuda/image/service/ImageService.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java
  src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
Labels: feature🌱

#126 feature/#125 content가 없는 신고 필터링 추가
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NullReportException.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreReportService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#129 feature/#124 리뷰 이미지 업데이트, 삭제 시 이미지 삭제 구현
  src/main/java/com/pd/gilgeorigoreuda/community/service/CommunityService.java
  src/main/java/com/pd/gilgeorigoreuda/image/service/ImageService.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/ReviewImage.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
Labels: feature🌱

#132 feature/#131 리뷰 이미지 연관 관계로 넣도록 초기화
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
Labels: refactor🛠️

#134 feature/#133 리뷰 이미지 등록시 이미지에 리뷰 아이디 가지고 들어가도록 수정
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewCreateRequest.java
Labels: refactor🛠️

#136 refactor/#130 kakao 소셜 로그인 및 회원가입, 토큰 생성 구현
  .gitignore
  build.gradle
  logs/error/2023-11-14.log
  logs/info/2023-11-14.log
  logs/warn/2023-11-14.log
  src/main/java/com/pd/gilgeorigoreuda/auth/controller/AuthController.java
  src/main/java/com/pd/gilgeorigoreuda/auth/dto/response/LoginResponse.java
  src/main/java/com/pd/gilgeorigoreuda/auth/exception/EmailDuplicatedException.java
  src/main/java/com/pd/gilgeorigoreuda/auth/service/AuthService.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/login/controller/LoginController.java
  src/main/java/com/pd/gilgeorigoreuda/login/controller/LoginTestController.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/MemberToken.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/OauthAccessToken.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/OauthProvider.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/OauthProviders.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/OauthUserInfo.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/RefreshToken.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/oauthuserinfo/KakaoUserInfo.java
  src/main/java/com/pd/gilgeorigoreuda/login/dto/request/LoginRequest.java
  src/main/java/com/pd/gilgeorigoreuda/login/dto/response/AccessTokenResponse.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/ExpiredPeriodAccessTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/ExpiredPeriodRefreshTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/InvalidAccessTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/InvalidAuthorizationCodeException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/InvalidRefreshTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/NotSupportedOauthServiceException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/RenewalAccessTokenFailException.java
  src/main/java/com/pd/gilgeorigoreuda/login/jwt/BearerTokenExtractor.java
  src/main/java/com/pd/gilgeorigoreuda/login/jwt/JwtProvider.java
  src/main/java/com/pd/gilgeorigoreuda/login/provider/KakaoOauthProvider.java
  src/main/java/com/pd/gilgeorigoreuda/login/repository/RefreshTokenRepository.java
  src/main/java/com/pd/gilgeorigoreuda/login/service/LoginService.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/Member.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreReportMemberResponse.java
  src/main/resources/application-local.yml
Labels: feature🌱, refactor🛠️

#140 feature/#137 접근 권한 검증
  src/main/java/com/pd/gilgeorigoreuda/auth/CheckIsMember.java
  src/main/java/com/pd/gilgeorigoreuda/auth/MemberInfo.java
  src/main/java/com/pd/gilgeorigoreuda/auth/MemberOnly.java
  src/main/java/com/pd/gilgeorigoreuda/auth/domain/Authority.java
  src/main/java/com/pd/gilgeorigoreuda/auth/domain/LoginMember.java
  src/main/java/com/pd/gilgeorigoreuda/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/com/pd/gilgeorigoreuda/auth/exception/UnAuthorizedException.java
  src/main/java/com/pd/gilgeorigoreuda/auth/resolver/MemberInfoArgumentResolver.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/web/ResolverConfig.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/test/java/com/pd/gilgeorigoreuda/HealthControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
Labels: feature🌱

#143 bug/#142 bean name duplicate
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/job/MemberActiveInfoUpdateJob.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberActiveInfoScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberLevelScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/service/MemberActiveInfoService.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/service/MemberLevelService.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/job/StoreReportAndBlockJob.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreReportUpdateScheduler.java
Labels: bug🐛

#145 bug/#144 bean duplicate error fix
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberActiveInfoScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreReportUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/batch/BatchConfig.java
Labels: bug🐛

#146 feature/#141 JwtProvider Test Code
  src/main/java/com/pd/gilgeorigoreuda/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/com/pd/gilgeorigoreuda/auth/exception/UnAuthorizedException.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/GilgeoriGoreudaException.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/GlobalControllerAdvice.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/EmptyImageListException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/ExceedImageCapacityException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/ExceedImageListSizeException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/FileImageNameHashException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/ImageNullException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/InvalidImageFileException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/InvalidImagePathException.java
  src/main/java/com/pd/gilgeorigoreuda/image/exception/InvalidImageUrlException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/ExpiredPeriodAccessTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/ExpiredPeriodRefreshTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/InvalidAccessTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/InvalidAuthorizationCodeException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/InvalidRefreshTokenException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/NotSupportedOauthServiceException.java
  src/main/java/com/pd/gilgeorigoreuda/login/exception/RenewalAccessTokenFailException.java
  src/main/java/com/pd/gilgeorigoreuda/login/jwt/JwtProvider.java
  src/main/java/com/pd/gilgeorigoreuda/member/exception/NoSuchMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/AlreadyExistInBoundaryException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/AlreadyReporterMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/BusinessDateResponseReflectionException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/LimitDistanceReportException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoOwnerMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoRepoterMemberException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchFoodTypeException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchPurchaseTypeException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchReportException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreReportHistoryException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NoSuchStoreTypeException.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/NullReportException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/NoSuchStoreVisitRecordException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/OutOfBoundaryException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/TimeOutException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/TooLongDistanceException.java
  src/test/java/com/pd/gilgeorigoreuda/login/jwt/JwtProviderTest.java
Labels: feature🌱, test🩺

#152 bug/#151 FoodCategory 연관관계 메소드를 통한 영속문제 수정
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodCategory.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
Labels: bug🐛, refactor🛠️

#154 feature/#153 가게 조회에 현재 사용자 위치에서 가게 위치 거리 응답 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java
  src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
Labels: feature🌱

#158 refactor/#150 store에서 review 조회시 내림차순 정렬 적용
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
Labels: refactor🛠️

#157 feature/#155 db master slave
  src/main/java/com/pd/gilgeorigoreuda/batch/member/job/MemberActiveInfoUpdateJob.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberActiveInfoScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/service/MemberActiveInfoService.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreAvgUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreReportUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreVisitUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceType.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/RoutingDataSource.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StoreService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#160 feature/#156 사용자 위치로 부터 가게 거리 계산을 위해 사용자 위경도 파라미터 추가
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/AddressSearchListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/AddressSearchResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/SearchStoreListResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/dto/response/SearchStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/FoodType.java
  src/test/java/com/pd/gilgeorigoreuda/search/repository/SearchRepositoryTest.java
  src/test/resources/application-test.yml
Labels: feature🌱

#162 refactor/#161 AccessToken 유효성 검사 로직 추가
  src/main/java/com/pd/gilgeorigoreuda/auth/CheckIsMember.java
  src/main/java/com/pd/gilgeorigoreuda/auth/resolver/MemberInfoArgumentResolver.java
  src/main/java/com/pd/gilgeorigoreuda/login/controller/LoginController.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/MemberAccessRefreshToken.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/MemberToken.java
  src/main/java/com/pd/gilgeorigoreuda/login/domain/RefreshToken.java
  src/main/java/com/pd/gilgeorigoreuda/login/jwt/JwtProvider.java
  src/main/java/com/pd/gilgeorigoreuda/login/repository/MemberTokenRepository.java
  src/main/java/com/pd/gilgeorigoreuda/login/repository/RefreshTokenRepository.java
  src/main/java/com/pd/gilgeorigoreuda/login/service/LoginService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
  src/test/java/com/pd/gilgeorigoreuda/auth/CheckIsMemberTest.java
  src/test/java/com/pd/gilgeorigoreuda/auth/resolver/MemberInfoArgumentResolverTest.java
  src/test/java/com/pd/gilgeorigoreuda/login/jwt/JwtProviderTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/store/controller/StoreControllerTest.java
Labels: feature🌱, refactor🛠️

#165 feature/#164 SearchController에 street_address 파라미터 추가
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
Labels: feature🌱

#167 feature/#163 검색한 주소를 통계 작업을 위해 저장하기 위한 로직 추가
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/repository/SearchRepository.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/test/java/com/pd/gilgeorigoreuda/search/repository/SearchRepositoryTest.java
Labels: feature🌱

#169 refactor/#166 카카오 redirect-url yml 수정
  src/main/resources/application-local.yml
Labels: refactor🛠️, hotfix🚨

#171 refactor/#170 KeywordRepository 수정
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
Labels: refactor🛠️, hotfix🚨

#173 feature/#172 검색 조건 파라미터들 마다 null 처리 및 하나의 어노테이션으로 통합하여 간소화
  src/main/java/com/pd/gilgeorigoreuda/common/config/web/ResolverConfig.java
  src/main/java/com/pd/gilgeorigoreuda/search/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/search/resolver/SearchParameter.java
  src/main/java/com/pd/gilgeorigoreuda/search/resolver/SearchParams.java
  src/main/java/com/pd/gilgeorigoreuda/search/resolver/SearchParamsArgumentResolver.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
Labels: feature🌱, refactor🛠️

#175 refactor/#174 좋아요순으로 정렬되도록 수정
  src/main/java/com/pd/gilgeorigoreuda/batch/review/scheduler/ReviewLikeHateBatchScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/community/controller/CommunityController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
Labels: refactor🛠️

#176 feature/#159 dev cd workflow
  .github/workflows/dev-cd.yml
  Dockerfile
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/RoutingDataSource.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feature🌱, DevOps⚙️

#178 bug/#177 dev-cd.yml 문법 오류 해결
  .github/workflows/dev-cd.yml
Labels: bug🐛, DevOps⚙️

#180 bug/#179 dev cd.yml
  .github/workflows/dev-cd.yml
  src/main/resources/application-prod.yml
Labels: bug🐛, DevOps⚙️

#182 bug/#181 dev-cd.yml working directory fix
  .github/workflows/ci.yml
  .github/workflows/dev-cd.yml
Labels: bug🐛, DevOps⚙️

#184 bug/#183 dev-cd.yml Dockerfile 경로 수정
  .github/workflows/dev-cd.yml
Labels: bug🐛, DevOps⚙️

#186 bug/#185 Dockerfile jar file 경로 수정
  Dockerfile
Labels: bug🐛, DevOps⚙️

#189 bug/#187 docker build 에서 deploy 단계로 넘어가지 않는 문제 해결
  .github/workflows/dev-cd.yml
Labels: bug🐛, DevOps⚙️

#191 bug/#190 runs-on을 ubuntu-latest로 변경
  .github/workflows/dev-cd.yml
Labels: bug🐛, DevOps⚙️

#193 bug/#192 docker image platform 변경
  .github/workflows/dev-cd.yml
Labels: bug🐛, DevOps⚙️

#195 refactor/#194 bean definition overide true 욥션 추가
  src/main/resources/application-dev.yml
Labels: refactor🛠️, hotfix🚨

#196 feature/#188 flyway 적용
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceType.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/RoutingDataSource.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V1__init.sql
Labels: feature🌱

#200 feature/#199 dev mysql docker compose
  docker-compose.yml
  src/main/resources/application-dev.yml
Labels: feature🌱, DevOps⚙️

#201 refactor/#198 멤버 토큰 검증으로 수정
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewPreferenceController.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StorePreferenceController.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreReportController.java
  src/main/java/com/pd/gilgeorigoreuda/visit/controller/VisitController.java
Labels: refactor🛠️

#204 refactor/#197 slave db
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/RoutingDataSource.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: refactor🛠️

#209 feature/#208 spring actuator 디펜던시 추가
  build.gradle
  src/main/resources/application-prod.yml
Labels: feature🌱

#216 bug/#215 prod-cd.yml 문법 오류 해결
  .github/workflows/prod-cd.yml
Labels: bug🐛, DevOps⚙️

#217 [release] 2차 prod 배포 테스트
  .github/workflows/prod-cd.yml
Labels: release⭐️

#220 [release] 3차 prod 배포 테스트
  .github/workflows/prod-cd.yml
Labels: release⭐️

#222 bug/#221 prod-cd.yml 문법 수정
  .github/workflows/prod-cd.yml
Labels: bug🐛

#226 [release] 5차 prod 배포
  .github/workflows/prod-cd.yml
Labels: release⭐️

#227 [release] 6차 prod 배포 테스트
  bluegreen.sh
Labels: release⭐️

#230 [release] 7차 prod 배포 테스트
  bluegreen.sh
Labels: release⭐️

#232 bug/#231 bluegreen.sh 문법 오류 해결
  bluegreen.sh
Labels: bug🐛

#233 [release] 8차 prod 배포 테스트
  bluegreen.sh
Labels: release⭐️

#235 bug/#234 bluegreen.sh 문법 수정
  .github/workflows/prod-cd.yml
  bluegreen.sh
Labels: bug🐛

#236 [release] 9차 prod 배포 테스트
  .github/workflows/prod-cd.yml
  bluegreen.sh
Labels: release⭐️

#238 bug/#237 bluegreen.sh
  bluegreen.sh
  src/main/resources/application-prod.yml
Labels: bug🐛

#239 [release] 10차 prod 배포 테스트
  bluegreen.sh
  src/main/resources/application-prod.yml
Labels: release⭐️

#241 feature/#240 cors config 설정 추가
  src/main/java/com/pd/gilgeorigoreuda/common/config/web/CorsConfig.java
Labels: feature🌱

#242 [release] 11차 prod 배포 테스트
  src/main/java/com/pd/gilgeorigoreuda/common/config/web/CorsConfig.java
Labels: release⭐️

#243 feature/prod-cd.yml 수정
  .github/workflows/prod-cd.yml
Labels: feature🌱

#244 [release] 11차 prod 배포 테스트
  .github/workflows/prod-cd.yml
Labels: release⭐️

#247 [release] 12차 prod 배포 테스트
  .github/workflows/prod-cd.yml
  bluegreen.sh
Labels: release⭐️

#249 refactor/#248 prod-cd.yml refactor
  .github/workflows/prod-cd.yml
Labels: refactor🛠️

#250 [release] 13차 prod 배포 테스트
  .github/workflows/prod-cd.yml
Labels: release⭐️

#252 feature/#251 applicaton-blue,green.yml
  .github/workflows/prod-cd.yml
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: feature🌱

#253 [release] 14차 prod 배포 테스트
  .github/workflows/prod-cd.yml
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: release⭐️

#256 refactor/#251 application.yml bluegreen
  .github/workflows/prod-cd.yml
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
  src/main/resources/application.yml
Labels: refactor🛠️

#257 [release] 16차 prod 배포 테스트
  .github/workflows/prod-cd.yml
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
  src/main/resources/application.yml
Labels: release⭐️

#259 [release] 17차 prod 배포 테스트
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: release⭐️

#260 [release] 18차 prod 배포 테스트
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
  src/main/resources/application.yml
Labels: release⭐️

#262 refactor/#261 application-blue,green.yml flyway 적용, ddl-auto validate…
  .github/workflows/prod-cd.yml
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: refactor🛠️

#265 feature/#264 add food_category table
  src/main/resources/db/migration/V2__foodcategory.sql
Labels: feature🌱

#266 [release] 19차 prod 배포 테스트
  src/main/resources/db/migration/V2__foodcategory.sql
Labels: feature🌱

#268 refactor/#267 init.sql
  src/main/resources/db/migration/V1__init.sql
Labels: refactor🛠️

#269 [release] 20차 prod 배포 테스트
  src/main/resources/db/migration/V1__init.sql
Labels: release⭐️

#272 [release] 21차 prod 배포 테스트
  src/main/resources/application-dev.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__foodcategory.sql
Labels: release⭐️

#273 bug/#270 flyway
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: bug🐛

#274 [release] 22차 prod 배포 테스트
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: release⭐️

#275 bug/#270 flyway 수정
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
Labels: bug🐛

#276 [release] 22차 prod 배포 테스트
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
Labels: release⭐️

#279 feature/#210 member info, member active info
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/Member.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/MemberActiveInfo.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/MemberLevel.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberActiveInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/member/service/MemberService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#282 refactor/#281 prod-cd.yml 수정 및 actuator 포트 변경
  .github/workflows/prod-cd.yml
  bluegreen.sh
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: refactor🛠️

#283 [release] 정식 1차 prod 배포
  .github/workflows/prod-cd.yml
  bluegreen.sh
  src/main/java/com/pd/gilgeorigoreuda/member/controller/MemberController.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/Member.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/MemberActiveInfo.java
  src/main/java/com/pd/gilgeorigoreuda/member/domain/entity/MemberLevel.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberActiveInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberRepository.java
  src/main/java/com/pd/gilgeorigoreuda/member/service/MemberService.java
  src/main/resources/application-blue.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-green.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: release⭐️

#285 [release] 2차 배포
  build.gradle
  src/main/resources/application-prod.yml
Labels: release⭐️

#286 [release] 3차 배포
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
  src/main/resources/application-prod.yml
Labels: release⭐️

#288 feature/#205 방문 인증한 유저만 리뷰 해당 가게 리뷰 작성 가능
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/NoAuthorityReviewException.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/NoSuchReviewException.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisitRecord.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/NotVerifiedVisitRecordException.java
Labels: feature🌱

#291 [release] 4차 배포
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/NoAuthorityReviewException.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/NoSuchReviewException.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreVisitRecord.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/NotVerifiedVisitRecordException.java
  src/main/resources/logback-spring.xml
Labels: release⭐️

#292 refactor/#287 사용자 생성시 사용자 활동 정보도 같이 생성
  src/main/java/com/pd/gilgeorigoreuda/login/service/LoginService.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberActiveInfoRepository.java
Labels: refactor🛠️

#293 feature/#207 방문기록 중복 체크 로직 구현
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/DuplicatedVisitRecordException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
Labels: feature🌱

#295 feature/#294 LocalDateTime 형식 yyyy-MM-dd로 통일
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewResponse.java
Labels: feature🌱

#297 [release] 5차 배포
  src/main/java/com/pd/gilgeorigoreuda/common/exception/ExceptionType.java
  src/main/java/com/pd/gilgeorigoreuda/login/service/LoginService.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberPreferenceStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/MemberReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/member/repository/MemberActiveInfoRepository.java
  src/main/java/com/pd/gilgeorigoreuda/visit/exception/DuplicatedVisitRecordException.java
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
Labels: release⭐️

#299 refactor/#298 주석, 불필요 코드 제거
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
  src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
  src/main/java/com/pd/gilgeorigoreuda/fileUpload/service/FileUploadService.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/PreferredStoreInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
  src/main/resources/application-green.yml
Labels: refactor🛠️

#300 [release] 6차 배포
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberActiveInfoScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberLevelScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreAvgUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreReportUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreVisitUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/database/DataSourceConfiguration.java
  src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
  src/main/java/com/pd/gilgeorigoreuda/fileUpload/service/FileUploadService.java
  src/main/java/com/pd/gilgeorigoreuda/member/dto/response/PreferredStoreInfoResponse.java
  src/main/java/com/pd/gilgeorigoreuda/search/service/SearchService.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
  src/main/resources/application-green.yml
Labels: release⭐️

#302 [release] 7차 배포
  src/main/resources/application-green.yml
Labels: release⭐️

#305 [release] 8차 배포
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
Labels: release⭐️

#307 refactor/#306 프로덕션 환경 show sql false로 변경
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: refactor🛠️

#308 [release] 9차 배포
  src/main/resources/application-blue.yml
  src/main/resources/application-green.yml
Labels: release⭐️

#310 refactor/#309 가게까지 대략적인 도보 시간 계산 수정
  src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
Labels: release⭐️

#311 [release] 9차 배포
  src/main/java/com/pd/gilgeorigoreuda/common/util/DistanceCalculator.java
Labels: release⭐️

#312 monitoring 설정
  build.gradle
  src/main/java/com/pd/gilgeorigoreuda/batch/member/scheduler/MemberLevelScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/review/scheduler/ReviewLikeHateBatchScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreAvgUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreReportUpdateScheduler.java
  src/main/java/com/pd/gilgeorigoreuda/batch/store/scheduler/StoreVisitUpdateScheduler.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback.xml
  src/main/resources/loki-appender.xml
Labels: feature🌱

#314 refactor/#313 도보 시간 시 단위로 수정
  src/main/java/com/pd/gilgeorigoreuda/visit/service/VisitService.java
Labels: refactor🛠️

#318 [release] 11차 배포
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/resources/db/migration/V2__increasebusinessdatecolumn.sql
Labels: release⭐️
