Repository gilgeori-goreuda/backend, pull requests merged in 2023-10, with the labels that each got.

#2 [Setting] 프로젝트 초기 환경 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/auth/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/common/exception/GilgeorigoreudaException.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/exception/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/domain/entity/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/exception/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/user/service/package-info.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplicationTests.java
Labels: setting💻

#9 feature/#8 keyword insert
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/Keyword.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/event/KeywordEvent.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/SearchService.java
Labels: feature🌱

#12 Feature/#11 Jacoco와 Codecov를 이용한 테스트 자동화(CI)
  .github/workflows/ci.yml
  build.gradle
  codecov.yml
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/HealthController.java
  src/main/java/com/pd/gilgeorigoreuda/common/config/JpaConfig.java
  src/main/resources/application-local.yml
  src/test/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplicationTests.java
  src/test/java/com/pd/gilgeorigoreuda/HealthControllerTest.java
Labels: feature🌱, refactor🛠️, setting💻

#16 feature/#13 StoreController 구현
  src/main/java/com/pd/gilgeorigoreuda/common/config/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StoreController.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/Store.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StoreLocation.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/BusinessDateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreCreateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreLocationRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreCreateResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreLocationResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/StoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/UpdateStoreResponse.java
  src/main/java/com/pd/gilgeorigoreuda/store/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/store/exception/BusinessDateResponseReflectionException.java
Labels: feature🌱, refactor🛠️

#24 feature/#21 리뷰 등록 기능 구현
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ImageRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/package-info.java
  src/test/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepositoryTest.java
Labels: feature🌱

#28 Feature/#21 review r
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/test/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepositoryTest.java
Labels: feature🌱

#22 Feature/#10 auto statistics
  src/main/java/com/pd/gilgeorigoreuda/GilgeoriGoreudaApplication.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/domain/Keyword.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/dto/response/KeywordResponse.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/repository/KeywordRepository.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/schedule/KeywordSchedule.java
  src/main/java/com/pd/gilgeorigoreuda/statistics/service/KeywordService.java
  src/main/java/com/pd/gilgeorigoreuda/store/controller/SearchController.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/SearchService.java
Labels: feature🌱

#29 리뷰삭제
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/resources/application-local.yml
Labels: feature🌱

#31 feature/#21 리뷰 CRUD 기능
  src/main/java/com/pd/gilgeorigoreuda/review/controller/ReviewController.java
  src/main/java/com/pd/gilgeorigoreuda/review/controller/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/domain/entity/Review.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/ReviewRequest.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/request/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/ReviewResponse.java
  src/main/java/com/pd/gilgeorigoreuda/review/dto/response/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ImageRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepository.java
  src/main/java/com/pd/gilgeorigoreuda/review/repository/package-info.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/ReviewService.java
  src/main/java/com/pd/gilgeorigoreuda/review/service/package-info.java
  src/main/resources/application-local.yml
  src/test/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepositoryTest.java
Labels: feature🌱

#36 refactor/#35 Storefavorites -> StorePreferences로 이름 변경
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreference.java
  src/main/resources/application-local.yml
  src/test/resources/application-test.yml
  src/test/resources/dummy_data.sql
Labels: refactor🛠️

#37 Feature/#32 store preference add
  src/main/java/com/pd/gilgeorigoreuda/store/controller/StorePreferenceController.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreference.java
  src/main/java/com/pd/gilgeorigoreuda/store/domain/entity/StorePreferenceType.java
  src/main/java/com/pd/gilgeorigoreuda/store/repository/StorePreferenceRepository.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/StorePreferenceService.java
  src/main/java/com/pd/gilgeorigoreuda/store/service/package-info.java
  src/main/resources/application-local.yml
Labels: feature🌱

#38 setting/#25 test template setting
  build.gradle
  src/test/java/com/pd/gilgeorigoreuda/review/repository/ReviewRepositoryTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ControllerTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/RepositoryTest.java
  src/test/java/com/pd/gilgeorigoreuda/settings/ServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/dummy_data.sql
Labels: feature🌱, setting💻
